

dataSource:
  name: 
  minPoolSize:  '5'
  maxPoolSize:  '10'
  maxWaitTime:  '10000'
  userName: root
  password: Root@123
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/appoitment?serverTimezone=UTC
  
